### ISSUE TITLE
RIA command not available on mac 

### ISSUE THREAD

**Issue by asida18** [RIAEvangelist/ria-app-framework#1]
You have to manually create to bashrc and add path to bashrc file. 
This should work automatically when install.sh is run.

**Comment by RIAEvangelist** [comment]
Thanks @asida18 will fix in an upcoming release.

**Comment by RIAEvangelist** [comment]
The install process needs to be fixed. There are more bugs related to how the created projects get shared across multiple users as well.

**Comment by RIAEvangelist** [comment]
This version to be deprecated. Issue addressed in next rev.
