### ISSUE TITLE
Proposed Feature request 

### ISSUE THREAD

**Issue by mrvini** [RIAEvangelist/ria-app-framework#2]
To be fully usable, it would be great to have the following features
1 Global Error Handler 
2. Installation permissions are off on Ubuntu
3. I would like to see external library folder on the same level as core and module
4. Resources folder is an ideal place to store images, fonts, etc....
5. Navigational/Layout template file with layout plugin would be a plus
6. if application could be split modules into view (with controllers, html and css) , models, and other layers, or simply say modules without any of the css, html

**Comment by RIAEvangelist** [comment]
This version to be deprecated. Issue addressed in next rev.
